@echo off
REM Remove HTML artifacts from Git
REM These are Pelican-generated files that Jekyll will generate automatically

echo Removing HTML artifacts from Git...
echo.

REM Remove root-level generated HTML
git rm about/index.html 2>nul
git rm my-collection/index.html 2>nul
git rm personal-projects/index.html 2>nul
git rm projects/index.html 2>nul
git rm school-projects/index.html 2>nul

REM Remove author pages
git rm -r author/ 2>nul

REM Remove category pages
git rm -r category/ 2>nul

REM Remove post pages
git rm -r posts/ 2>nul

REM Remove tag pages
git rm -r tag/ 2>nul

REM Remove typewriter individual pages (but keep typewriters.html and typewriters/*.md)
REM First, remove typewriters/index.html if it exists
git rm typewriters/index.html 2>nul
REM Then remove all typewriter subdirectory index.html files
for /d %%d in (typewriters\*) do (
    if exist "%%d\index.html" (
        git rm "%%d\index.html" 2>nul
    )
)

echo.
echo HTML artifacts removed from Git tracking.
echo.
echo Note: These files are generated by Jekyll automatically.
echo Jekyll will recreate them when you run serve.bat or build.bat.
echo.
pause

